# Copyright (C) 2021 SwastikNath Group Holdings LLC.
# This app is an intellectual property of SwastikNath Group LLC.
# No Parts of this app, source code can be reproduced in any form
# without prior written permissions from SwastikNath Group Holdings
# and any of its affiliates.

name: anuranan_sahitya_app
description: Anuranan Sahitya Gosthi's Official App for Writers.

publish_to: 'none'

version: 0.0.8+184

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  animated_text_kit: ^3.1.0
  loading: ^1.0.2
  flutter_local_auth_invisible: ^1.1.0
  font_awesome_flutter: ^8.11.0
  flutter_sliding_up_panel: ^1.1.0+1
  syncfusion_flutter_charts: ^18.4.42
  syncfusion_flutter_core: ^18.4.42
  flutter_easyloading: ^2.2.2
  google_sign_in: "^4.5.1"
  #  flutter_facebook_auth: "^1.0.0"
  firebase_core: "0.7.0"
  github_sign_in: ^0.0.1
  firebase_auth: ^0.20.0+1
  lottie: ^0.7.0+1
  rflutter_alert: ^1.1.0
  expanding_button: ^1.0.2
  modal_bottom_sheet: ^1.0.0
  avatar_glow: ^1.2.0
  intro_views_flutter: '^2.8.2'
  widget_circular_animator: ^0.1.5+1
  google_nav_bar: ^3.2.0
  line_icons: ^0.2.0
  expansion_card: ^0.1.0
  weather_icons: ^2.0.2
  fab_circular_menu: ^1.0.1
  slimy_card: ^1.0.4
  carousel_slider: ^3.0.0
  google_fonts: ^1.1.2
  sign_button: ^1.0.1
  hb_check_code: ^0.0.1
  shrink_sidemenu: ^1.0.0+3
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Jetbrains Mono
      fonts:
        - asset: fonts\JetBrainsMonoBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
